# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hzq/NVIDIA_CUDA-9.0_Samples/3_Imaging/cudaHardDecodeRtsp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hzq/NVIDIA_CUDA-9.0_Samples/3_Imaging/cudaHardDecodeRtsp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hzq/NVIDIA_CUDA-9.0_Samples/3_Imaging/cudaHardDecodeRtsp/CMakeFiles /home/hzq/NVIDIA_CUDA-9.0_Samples/3_Imaging/cudaHardDecodeRtsp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hzq/NVIDIA_CUDA-9.0_Samples/3_Imaging/cudaHardDecodeRtsp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hdDemo

# Build rule for target.
hdDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdDemo
.PHONY : hdDemo

# fast build rule for target.
hdDemo/fast:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/build
.PHONY : hdDemo/fast

src/FrameQueue.o: src/FrameQueue.cpp.o

.PHONY : src/FrameQueue.o

# target to build an object file
src/FrameQueue.cpp.o:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/FrameQueue.cpp.o
.PHONY : src/FrameQueue.cpp.o

src/FrameQueue.i: src/FrameQueue.cpp.i

.PHONY : src/FrameQueue.i

# target to preprocess a source file
src/FrameQueue.cpp.i:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/FrameQueue.cpp.i
.PHONY : src/FrameQueue.cpp.i

src/FrameQueue.s: src/FrameQueue.cpp.s

.PHONY : src/FrameQueue.s

# target to generate assembly for a file
src/FrameQueue.cpp.s:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/FrameQueue.cpp.s
.PHONY : src/FrameQueue.cpp.s

src/MainDemo.o: src/MainDemo.cpp.o

.PHONY : src/MainDemo.o

# target to build an object file
src/MainDemo.cpp.o:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/MainDemo.cpp.o
.PHONY : src/MainDemo.cpp.o

src/MainDemo.i: src/MainDemo.cpp.i

.PHONY : src/MainDemo.i

# target to preprocess a source file
src/MainDemo.cpp.i:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/MainDemo.cpp.i
.PHONY : src/MainDemo.cpp.i

src/MainDemo.s: src/MainDemo.cpp.s

.PHONY : src/MainDemo.s

# target to generate assembly for a file
src/MainDemo.cpp.s:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/MainDemo.cpp.s
.PHONY : src/MainDemo.cpp.s

src/NvDecode.o: src/NvDecode.cpp.o

.PHONY : src/NvDecode.o

# target to build an object file
src/NvDecode.cpp.o:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/NvDecode.cpp.o
.PHONY : src/NvDecode.cpp.o

src/NvDecode.i: src/NvDecode.cpp.i

.PHONY : src/NvDecode.i

# target to preprocess a source file
src/NvDecode.cpp.i:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/NvDecode.cpp.i
.PHONY : src/NvDecode.cpp.i

src/NvDecode.s: src/NvDecode.cpp.s

.PHONY : src/NvDecode.s

# target to generate assembly for a file
src/NvDecode.cpp.s:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/NvDecode.cpp.s
.PHONY : src/NvDecode.cpp.s

src/cudaModuleMgr.o: src/cudaModuleMgr.cpp.o

.PHONY : src/cudaModuleMgr.o

# target to build an object file
src/cudaModuleMgr.cpp.o:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/cudaModuleMgr.cpp.o
.PHONY : src/cudaModuleMgr.cpp.o

src/cudaModuleMgr.i: src/cudaModuleMgr.cpp.i

.PHONY : src/cudaModuleMgr.i

# target to preprocess a source file
src/cudaModuleMgr.cpp.i:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/cudaModuleMgr.cpp.i
.PHONY : src/cudaModuleMgr.cpp.i

src/cudaModuleMgr.s: src/cudaModuleMgr.cpp.s

.PHONY : src/cudaModuleMgr.s

# target to generate assembly for a file
src/cudaModuleMgr.cpp.s:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/cudaModuleMgr.cpp.s
.PHONY : src/cudaModuleMgr.cpp.s

src/cudaProcessFrame.o: src/cudaProcessFrame.cpp.o

.PHONY : src/cudaProcessFrame.o

# target to build an object file
src/cudaProcessFrame.cpp.o:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/cudaProcessFrame.cpp.o
.PHONY : src/cudaProcessFrame.cpp.o

src/cudaProcessFrame.i: src/cudaProcessFrame.cpp.i

.PHONY : src/cudaProcessFrame.i

# target to preprocess a source file
src/cudaProcessFrame.cpp.i:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/cudaProcessFrame.cpp.i
.PHONY : src/cudaProcessFrame.cpp.i

src/cudaProcessFrame.s: src/cudaProcessFrame.cpp.s

.PHONY : src/cudaProcessFrame.s

# target to generate assembly for a file
src/cudaProcessFrame.cpp.s:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/cudaProcessFrame.cpp.s
.PHONY : src/cudaProcessFrame.cpp.s

src/dynlink_cuda.o: src/dynlink_cuda.cpp.o

.PHONY : src/dynlink_cuda.o

# target to build an object file
src/dynlink_cuda.cpp.o:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/dynlink_cuda.cpp.o
.PHONY : src/dynlink_cuda.cpp.o

src/dynlink_cuda.i: src/dynlink_cuda.cpp.i

.PHONY : src/dynlink_cuda.i

# target to preprocess a source file
src/dynlink_cuda.cpp.i:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/dynlink_cuda.cpp.i
.PHONY : src/dynlink_cuda.cpp.i

src/dynlink_cuda.s: src/dynlink_cuda.cpp.s

.PHONY : src/dynlink_cuda.s

# target to generate assembly for a file
src/dynlink_cuda.cpp.s:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/dynlink_cuda.cpp.s
.PHONY : src/dynlink_cuda.cpp.s

src/dynlink_nvcuvid.o: src/dynlink_nvcuvid.cpp.o

.PHONY : src/dynlink_nvcuvid.o

# target to build an object file
src/dynlink_nvcuvid.cpp.o:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/dynlink_nvcuvid.cpp.o
.PHONY : src/dynlink_nvcuvid.cpp.o

src/dynlink_nvcuvid.i: src/dynlink_nvcuvid.cpp.i

.PHONY : src/dynlink_nvcuvid.i

# target to preprocess a source file
src/dynlink_nvcuvid.cpp.i:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/dynlink_nvcuvid.cpp.i
.PHONY : src/dynlink_nvcuvid.cpp.i

src/dynlink_nvcuvid.s: src/dynlink_nvcuvid.cpp.s

.PHONY : src/dynlink_nvcuvid.s

# target to generate assembly for a file
src/dynlink_nvcuvid.cpp.s:
	$(MAKE) -f CMakeFiles/hdDemo.dir/build.make CMakeFiles/hdDemo.dir/src/dynlink_nvcuvid.cpp.s
.PHONY : src/dynlink_nvcuvid.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... hdDemo"
	@echo "... edit_cache"
	@echo "... src/FrameQueue.o"
	@echo "... src/FrameQueue.i"
	@echo "... src/FrameQueue.s"
	@echo "... src/MainDemo.o"
	@echo "... src/MainDemo.i"
	@echo "... src/MainDemo.s"
	@echo "... src/NvDecode.o"
	@echo "... src/NvDecode.i"
	@echo "... src/NvDecode.s"
	@echo "... src/cudaModuleMgr.o"
	@echo "... src/cudaModuleMgr.i"
	@echo "... src/cudaModuleMgr.s"
	@echo "... src/cudaProcessFrame.o"
	@echo "... src/cudaProcessFrame.i"
	@echo "... src/cudaProcessFrame.s"
	@echo "... src/dynlink_cuda.o"
	@echo "... src/dynlink_cuda.i"
	@echo "... src/dynlink_cuda.s"
	@echo "... src/dynlink_nvcuvid.o"
	@echo "... src/dynlink_nvcuvid.i"
	@echo "... src/dynlink_nvcuvid.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

